// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Header: typeof import('./components/Header.vue')['default']
    IvueChip: typeof import('ivue-material-plus/dist/unplugin-vue-components/es')['IvueChip']
    IvueIcon: typeof import('ivue-material-plus/dist/unplugin-vue-components/es')['IvueIcon']
    IvueOption: typeof import('ivue-material-plus/dist/unplugin-vue-components/es')['IvueOption']
    IvuePopover: typeof import('ivue-material-plus/dist/unplugin-vue-components/es')['IvuePopover']
    IvueSelect: typeof import('ivue-material-plus/dist/unplugin-vue-components/es')['IvueSelect']
    Settings: typeof import('./components/Settings.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('ivue-material-plus/dist/unplugin-vue-components/es')['IvueLoading']
  }
}
